### ISSUE TITLE
Opening fence gates?

### ISSUE THREAD

**Issue by BGLT** [seymourimadeit/guardvillager-suggestions#102]
Hello! First, I'd like to mention that this is easily one of my favorite mods out there, always finds a way into my modded experiences. However, see often that, especially with mods that enhance village structures, guards and villagers alike tend to get stuck in fenced areas. Since I see general AI changes are part of this mod, maybe villagers and guards being able to open and shut fence gates could be added? Might be a small gripe, but when a Zombie hoard or Raid shows up it would be nice to have all the guards not fenced in with my cows lol.

**Comment by seymourimadeit** [comment]
added in big brain 

i'm might add the unrelated ai changes inside big brain too when i port to 1.19
