### ISSUE TITLE
Guard villagers use resource pack villager skins

### ISSUE THREAD

**Issue by mimi-min** [seymourimadeit/guardvillager-suggestions#114]
I use a resource pack (Mizuno's Craft) that turns the default villagers into animals, as you can see here: https://i.imgur.com/00BW40n.jpeg

As such, the guard villagers look pretty out of place...

I was wondering if it would be possible to make it so that guard villagers would use the resource pack's villager skins. 
Alternatively, is there a way to manually skin them (edit the resource pack to add custom skins)?

Thanks in advance, and keep up the good work!

**Comment by seymourimadeit** [comment]
You can make your own texture pack that gives the guards the animal skins, same process as vanilla, except you target the guard villagers asset files

**Comment by mimi-min** [comment]
Thanks, good to know!
