### ISSUE TITLE
Guards get upset if you rob villager chests

### ISSUE THREAD

**Issue by CasualJeremy** [seymourimadeit/guardvillager-suggestions#119]
Minecraft might be one of the only games were you can fully rob an entire town and the villagers will still love you. It would be nice if there was a toggle-able feature were guards would get upset if you get caught sifting through someone else's belongings. 

Maybe going through the chest would give you the a status effect called 'Wanted' as the opposition of 'Hero of the Village'?

**Comment by omeggga** [comment]
Okay but why though? Villagers don't even use chests for anything at all. The last thing I want is to come back from mining and every guard villager to throw hands because I opened a chest in my own home that happens to be in the village.

**Comment by CasualJeremy** [comment]
Well that's why it would be turned off by default but an option in general. In every other game I've played if you mess with people in villages they tend to get upset. 

This would give modpack creators the option to add more immersion to their creations if they so choose.
