### ISSUE TITLE
Villager AI

### ISSUE THREAD

**Issue by Looodon** [seymourimadeit/guardvillager-suggestions#123]
Minecraft version: 1.19.2

Hey, Idk if this is a bug or intended, but some villagers seem to be following the guards around instead of going to bed at night. I read through the config to see if there's a way to turn that off and didn't find one. Would you guys consider adding the option to turn that off someday? Thanks for your time!

**Comment by Looodon** [comment]
The problem with the villagers following the guards (especially at night) is the guards walk far away from the village to fight hostile mobs and the villagers follow them away from the village and get lost and die

**Comment by xenornithos** [comment]
Agreed, I would also prefer it disabled -- could there please be an option in the configs to toggle whether or not villagers follow the guards?

**Comment by Looodon** [comment]
id love to re-download the mod if this is resolved someday cuz it was getting my villagers killed due to the them following the guards into dangerous locations and dying

**Comment by seymourimadeit** [comment]
This issue is solved
