### ISSUE TITLE
Put the guards to be able to ride the horse.

### ISSUE THREAD

**Issue by Morkyz** [seymourimadeit/guardvillager-suggestions#126]
Put the guards to be able to ride the horse

**Comment by omeggga** [comment]
Problem with that is: what then? Fighting on horseback in minecraft is the most "meh" way to fight there is. There is no damage boost when you charge at an enemy with a horse, not to mention the way these villagers fight, backpedalling to avoid the enemy getting too close, a horse would hinder them.

**Comment by seymourimadeit** [comment]
I know this post was made almost a year ago but I figured I should put this here for any future suggestions regarding guards riding horses.

After some testing myself I figured that most horses normally spawned are actually slower than the guards themselves, making the horse's main point (being a fast transportation option) moot. Therefore guards riding horses naturally is very unlikely.
