### ISSUE TITLE
Consider open-source license for resource files

### ISSUE THREAD

**Issue by poly2it** [seymourimadeit/guardvillager-suggestions#138]
It seems that many (if not most) of these assets are inherited from resources by Mojang, so it doesn't even make sense to claim rights on them. Doing this would have the benefit of simplifying licensing, which for example would help with mod-pack development.

**Comment by seymourimadeit** [comment]
Go inquire with the artist of the mod, HadeZ about this. They and I discussed this after the assets were used unauthorized by someone else for a public resource pack and we mutually agreed upon using the license. 

If you have an edge-case in which the assets of the mod have to be used, discussing with the artist themselves would be the best bet.
