### ISSUE TITLE
Please make it editable in config that guard will never attack player though hurt by player with incaution 

### ISSUE THREAD

**Issue by betterworld-sjq** [seymourimadeit/guardvillager-suggestions#152]
Guards are great helpers in raid.But if I don't have Hero of the Village,I by chance hit a guard when swording illagers,the guards will immediately attack towards me.
I know in vallina Minecraft, Iron Golems will act the same way but there's a mod called 'Liberty's Villagers' which has config that Iron Golem natrually spawned in village will never attack player though hit, and that well solves the problem when I hit village's Golem during raid.

**Comment by seymourimadeit** [comment]
Addressed in newest update via blacklist improvements

**Comment by Djeguer** [comment]
hello, how do we do it? even if I put my nickname on the blacklist, it doesn't work.

**Comment by seymourimadeit** [comment]
> hello, how do we do it? even if I put my nickname on the blacklist, it doesn't work.

put "minecraft:player" in the blacklist

**Comment by Djeguer** [comment]
> > hello, how do we do it? even if I put my nickname on the blacklist, it doesn't work.
> 
> put "minecraft:player" in the blacklist

it doesn't work, even putting the text in the channel, they still attack me

![Sans titre](https://github.com/seymourimadeit/guardvillager-suggestions/assets/154885931/25af0517-0b53-4df5-9ab8-2e2418da3cfa)

**Comment by seymourimadeit** [comment]
Restart your game.

**Comment by Djeguer** [comment]
it's done but it doesn't work at all, even shooting friends doesn't work, in a melee everyone hits everyone

even with a new game
