### ISSUE TITLE
Add zh_cn translation

### ISSUE THREAD

**Issue by v191949v** [seymourimadeit/guardvillager-suggestions#156]
{
"entity.guardvillagers.guard": "警卫",
"item.guardvillagers.guard_spawn_egg": "警卫刷怪蛋",
"item.guardvillagers.illusioner_spawn_egg": "幻术师刷怪蛋",
"item.guardvillagers.iron_golem_spawn_egg": "铁傀儡刷怪蛋",
"item.guardvillagers.snow_golem_spawn_egg": "雪傀儡刷怪蛋",
"guardinventory.health": "生命值: %s",
"guardinventory.armor": "护甲值: %s",
"subtitles.entity.guard.ambient": "警卫：喃喃自语",
"subtitles.entity.guard.hurt": "警卫：受伤",
"subtitles.entity.guard.death": "警卫：死亡"
}

**Comment by seymourimadeit** [comment]
I appreciate this submission but I'd like it was submitted as a pull request with a lang file. If that is not possible for you I will gladly create the file myself if I have the time. The pull request is just so you show up in the contributors section of the mod's github repo.
