### ISSUE TITLE
compartible better combat

### ISSUE THREAD

**Issue by himansure** [seymourimadeit/guardvillager-suggestions#159]

**Comment by Firelancer120** [comment]
spelling what your suggesting right helps. also a description is required lol

**Comment by himansure** [comment]
make the Guard had animation when attack like player

**Comment by seymourimadeit** [comment]
https://www.curseforge.com/minecraft/mc-mods/mob-player-animator 
https://www.curseforge.com/minecraft/mc-mods/better-mob-combat
