### ISSUE TITLE
Config for guard following players without hero effect

### ISSUE THREAD

**Issue by CrowOfDionysia** [seymourimadeit/guardvillager-suggestions#160]
Requiring hero of the village for villager following works good for reassignment patrol points, but for having an actual guard companion makes it pretty frustrating.

Having a config to change it potentially base it off of reputation instead would make the fantasy of building up an army much better.

**Comment by seymourimadeit** [comment]
already exists

**Comment by CrowOfDionysia** [comment]
i guess this feature just doesnt exist for 1.18? unless im just blind as hell

**Comment by seymourimadeit** [comment]
> i guess this feature just doesnt exist for 1.18? unless im just blind as hell

it only exists in the 1.19+ versions

**Comment by CrowOfDionysia** [comment]
aye. that sucks. still using the mod, great content regardless!
