### ISSUE TITLE
cant config

### ISSUE THREAD

**Issue by Firelancer120** [seymourimadeit/guardvillager-suggestions#166]
i try to change the general ai blacklist so that the guards will attack all hostile mobs EXCEPT creepers for obvious reasons. and just putting minecraft:creeper in the brackets like it tells you too. causes it to crash completely 
[crash-2023-12-06_15.07.39-client.txt](https://github.com/seymourimadeit/guardvillager-suggestions/files/13592647/crash-2023-12-06_15.07.39-client.txt)

**Comment by Firelancer120** [comment]
the fix i have currently is just delete the config and reopen it . and by default they now attack all hostile mobs. but the creeper blacklist doesnt stay i try to change it and it crashes. honestly biggest piss off

**Comment by seymourimadeit** [comment]
put in quotation marks like "minecraft:creeper" and for multiple entities "minecraft:creeper", "minecraft:skeleton"
