### ISSUE TITLE
Guards shoot farther than they can hit

### ISSUE THREAD

**Issue by minecraftedleen** [seymourimadeit/guardvillager-suggestions#171]
Guards shoot farther than they actually should if their target is far away and their arrows just hit the ground. This also causes friendly fire, either make it so guards aim higher when shooting far or not make them shoot too far.

**Comment by minecraftedleen** [comment]
the first option sounds better, maybe something like the enhanced ai mod pillagers which aim higher for farther targets (here is enhanced ai pillagers vs guards, you can see that guards that have a big distance from the pillagers cannot hit them

https://github.com/seymourimadeit/guardvillager-suggestions/assets/81533620/80ffed25-246c-4fe4-8129-21948c7ae475

**Comment by seymourimadeit** [comment]
Addressed in recent commit
