### ISSUE TITLE
Multi-Follow

### ISSUE THREAD

**Issue by MajorasYamask** [seymourimadeit/guardvillager-suggestions#178]
It'd be helpful if there was a way to set multiple guards in a village/village-sized area to follow mode at the same time, as opposed to setting each one to follow mode individually. I believe the main uses for this would be gathering guards for wide-scale improvements such as improving their weapons, and letting a player quickly gather an army for raids or similar fights.

**Comment by seymourimadeit** [comment]
Implemented in the next 1.21 update. I'll see if I can apply this change to a 1.20.1 update too but I'm not sure if I'm going to have a lot of time in my hands in the next few months.
