### ISSUE TITLE
Add a config that allows Guards to attack villagers/iron-gollums/and other guards.

### ISSUE THREAD

**Issue by OutlandJoe** [seymourimadeit/guardvillager-suggestions#179]
I understand that this might seem counter-productive but i'd love the ability to tell a guard to go execute a villager or another guard.

Mainly so that I could say, raid another village and have them kill it's villagers and guards.

There is the mod villager recruits that does that, but I would still love to see a simple config option to disable the villager/iron-gollum/guard blacklist when instructing guards to attack something.

**Comment by seymourimadeit** [comment]
This exists in the mod already due to how you can already remove those mobs from the default blacklist in 1.20 and up
