### ISSUE TITLE
Add configure option for list of passive mobs to attack

### ISSUE THREAD

**Issue by nmarshall23** [seymourimadeit/guardvillager-suggestions#19]
I would like a list in the config of passive mobs to attack along with a percentage chance they will attack when spotted. 

[Alex's Mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs) has several pests mobs. They are passive mobs so they don't attack villagers or players. 

For example: Raccoon and crows steal food.

**Comment by seymourimadeit** [comment]
implemented
