### ISSUE TITLE
1.12?

### ISSUE THREAD

**Issue by one211** [seymourimadeit/guardvillager-suggestions#27]
I'm sure this is asked to death, and already dismissed. But I was hoping for a 1.12.2 compatible version. I don't know how this would be possible from a coding/implementation standpoint as villager jobs aren't a thing in this version beyond static spawn jobs.

But I just wanted to ask for the sake of hope or confirmation. Awesome mod though, I appreciate all the fine details and how much more alive the villages feel. I used this in 1.14 and it was beautiful.

**Comment by seymourimadeit** [comment]
1.12 is dead. I won't make any mods for that anymore. This also goes for 1.14 and 1.15 too.
