### ISSUE TITLE
Lead on villagers?

### ISSUE THREAD

**Issue by Lakeno** [seymourimadeit/guardvillager-suggestions#35]
i noticed that you can put leads on the guard villagers, wich makes no sense since you cannot put leads on vanilla villagers. Not that big of a problem but its always good to improve. 

idk tho, is this a feature?

![2021-03-28_01 30 36](https://user-images.githubusercontent.com/81501542/112742485-5d9d7080-8f65-11eb-9cbf-4afa82187714.png)

**Comment by seymourimadeit** [comment]
What version are you on? This was removed in 1.2.0

**Comment by Lakeno** [comment]
> What version are you on? This was removed in 1.2.0

I was playing in 1.1.10, didnt noticed that it was updated, sorry for the incovinience.
