### ISSUE TITLE
Config Option, "Allow players to make guards follow only if they have hero of the village" = false

### ISSUE THREAD

**Issue by zemoire** [seymourimadeit/guardvillager-suggestions#38]
Please add an option that enables the "follow" button in the guard's inventory without the "hero of the village" effect.

We already have this:
"Allow players to give guards stuff only if they have the hero of the village effect?" = false
"Allow players to set guard patrol points only if they have hero of the village" = false
 
I guess it's fair to have:
"Allow players to make guards follow only if they have hero of the village" = false

Thank you thank you thank you :)))

**Comment by seymourimadeit** [comment]
Not everything needs to be configurable.
