### ISSUE TITLE
Support for Consecration Mod

### ISSUE THREAD

**Issue by SaltSouls** [seymourimadeit/guardvillager-suggestions#40]
Right now guard villagers plays really poorly with the Consecration mod. This is due to the weapons they use not being effective against the undead mobs. I feel like this can be mitigated by either having a version of the guards that use the tools added by the Consecration mod when installed, or by letting the player configure their default equipment via configs. I feel like the configs would be better as well as having an option to more randomly assign gear to the guards so that they don't all have the same equipment. That way some could have things like full iron while others maybe only have a leather tunic. Could make the guards seem a bit more like they are a ragtag team than a fully realized force before the player comes in to help.

**Comment by seymourimadeit** [comment]
You can make a datapack that modifies what things the guards spawn with, it's right in the FAQ. This issue will be closed due to the fact the things its asking (configuring default equipment via configs) already exists.

**Comment by SaltSouls** [comment]
Oh sweet. Sorry about that then. Must have missed that when looking through.
