### ISSUE TITLE
Guard Variant 'Mercenary'

### ISSUE THREAD

**Issue by GottJammern** [seymourimadeit/guardvillager-suggestions#42]
As the normal guard, except doesnt require hero of the village.
1) Spawn 1 for every 6 guards in the village to reward a player who defends one.
2) Will follow the player if hired. Can be hired via GUI, 1 emerald = 9 minecraft days.
3) Can designate a block they will stay near and attack enemies within a radius.

**Comment by seymourimadeit** [comment]
Why? This would literately make players ignore the regular guards, thus nullifying them, also having mobs that could wear god gear  obey the player forever is op as hell.
