### ISSUE TITLE
Guard Villagers tend to stuck on water and swims away

### ISSUE THREAD

**Issue by iloveShaders** [seymourimadeit/guardvillager-suggestions#44]
I have a packed village on the ocean that is constantly attacked from the seas, the Drowned mobs are luring those dumb Villagers into the ocean and they keep swim after them.

Would be great if they ignored Drowned as they ignore most other mobs...

**Comment by iloveShaders** [comment]
nobody cares

**Comment by Cendar** [comment]
> nobody cares

Wow what a condescendant way to say things but no we do care in fact because its kinda boring to see all your guard dying from a horde of drowned
