### ISSUE TITLE
Make guard pick up food items

### ISSUE THREAD

**Issue by warning-djkajslh** [seymourimadeit/guardvillager-suggestions#45]
Make farmers throw out food items at the villagers, and the guard can pick them up

**Comment by kristibektashi** [comment]
> Make farmers throw out food items at the villagers, and the guard can pick them up

Farmers already do that

**Comment by seymourimadeit** [comment]
> > Make farmers throw out food items at the villagers, and the guard can pick them up
> 
> Farmers already do that

They don't but I should actually make them do this.
