### ISSUE TITLE
consecration rebalance

### ISSUE THREAD

**Issue by kuba26038** [seymourimadeit/guardvillager-suggestions#52]
consecration is a mod that makes undead mobs practically unkillable unless they are on fire. since guards can't have enchanted swords, i suggest changing that and giving them a 50% chance of having swords enchanted with fire aspect 1 if the mod is present. it would be cool if the crossbow guards were able to use the new flaming arrows added by the mod, too, but it isn't necesary i hope.

**Comment by seymourimadeit** [comment]
You can edit what guards spawn with via a datapack.
