### ISSUE TITLE
[Suggestion] Prevent Guards spawning in Hostile Villages mod

### ISSUE THREAD

**Issue by smoothuk** [seymourimadeit/guardvillager-suggestions#59]
There's this cool little mod which gives villages a chance to spawn with monsters instead of villagers [https://www.curseforge.com/minecraft/mc-mods/hostile-villages](https://www.curseforge.com/minecraft/mc-mods/hostile-villages)

Problem is when combined with this mod, there's often guards alongside the hostile mobs.  It can lead to some interesting fights, but it would be nice to have the option to have guards not spawn in the case of a hostile village.

**Comment by seymourimadeit** [comment]
Mod's closed source, can't do much about it.
