### ISSUE TITLE
Problem with config file - attack all mobs blacklist

### ISSUE THREAD

**Issue by WholeMilkDoggy** [seymourimadeit/guardvillager-suggestions#70]
Editing the like that says "Mob BlackList" = []" at all results in Minecraft being unable to even start up.

Just getting fed up with my guards blindly charging at creepers and endermen and dying instantly.

Could this be a compatibility issue with other mods? Perhaps with Big Brain?
         edit: not a Big Brain issue

**Comment by seymourimadeit** [comment]
"Mob BlackList = []" should be formatted like this

Mob BlackList" = ["minecraft:creeper", "minecraft:skeleton"]

if you're leaving the mob ids without the quotes, it will crash.

also this isn't the place to post bug reports, please post them in the guardvillagers repo.
