### ISSUE TITLE
Suggestion:Allow us to config what guard villagers spawn and dont spawn with.

### ISSUE THREAD

**Issue by Frizzledizzley** [seymourimadeit/guardvillager-suggestions#78]
Basically if we wanted to have them use spartan weaponry or shields we'd have a config which would allow us to do that, or maybe some way of having them spawn in with different weapons than swords.

**Comment by FlameyFaucet** [comment]
I believe this is already possible with datapacks.

**Comment by seymourimadeit** [comment]
> I believe this is already possible with datapacks.

Yep.
