### ISSUE TITLE
As long as I add something to the blacklist of all monsters attacked by this guard here, the game will not open

### ISSUE THREAD

**Issue by rinhau** [seymourimadeit/guardvillager-suggestions#80]
![image](https://user-images.githubusercontent.com/93511743/139635569-b0d9c08e-82ee-42e1-be36-c163e7c0903f.png)
![image](https://user-images.githubusercontent.com/93511743/139635589-337fc8a2-ad69-4f0b-b9af-fa9ec97dfbb6.png)

**Comment by FlameyFaucet** [comment]
use quotes, so it'll be ["minecraft:creeper"]

**Comment by rinhau** [comment]
> 使用引号，所以它会是 ["minecraft:creeper"]

oh! thank you
