### ISSUE TITLE
Fabric Port Permission/Access?

### ISSUE THREAD

**Issue by skatemo** [seymourimadeit/guardvillager-suggestions#82]
surely, you get asked this a lot so sorry in advance for the inconvenience, but I personally love the idea of the mod, would love to be able to use it in fabric. Was wondering if the mod creator would be able/willing to grant access to porting abilities for personal use and enjoyment purposes or if it will remain Forge exclusive altogether

**Comment by DarkSoulMastery** [comment]
We already have a fabric port for 1.18 only https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric
