### ISSUE TITLE
Commanding Guards 

### ISSUE THREAD

**Issue by goldhero0112** [seymourimadeit/guardvillager-suggestions#83]
Make it so that when you have the hero of the village when you open their GUI you can tell them to follow you or stay when you put it on stay shouldn't affect the AI of the guard it should still attack hostile mobs it would make  for really awesome builds a lot more people would like it

**Comment by JustNerro** [comment]
Agree, I really want to create crossbowmen sentry posts without trapping them for life

**Comment by NotEvenThere** [comment]
Yeah, Good idea!

**Comment by seymourimadeit** [comment]
This already exists.
