### ISSUE TITLE
Durability?

### ISSUE THREAD

**Issue by oXperienZo** [seymourimadeit/guardvillager-suggestions#91]
This is more of a question and not an "issue" but I didn't see anywhere else to post questions so whatever. You can equip the guards with better armor and weapons, but does the durability of the equipment they use go down like for players or does it not? I would like to know whether there is any point in equipping them with mending and unbreaking enchanted armor and weapons.

**Comment by omeggga** [comment]
Durability goes down, and they don't get xp per kill so mending does nothing. Go for unbreaking.
