### ISSUE TITLE
crossbow tactical behavior like piglin?

### ISSUE THREAD

**Issue by Duy-84-231** [seymourimadeit/guardvillager-suggestions#93]
Yes, as the title, can you make guards (when use crossbow) go backwards when fight enemies like piglins? especially when using firework ammo

Oh, just copy all piglin's crossbow tactics lol, bcz the guards have no accuracy firing on long-range targets.

1 of my footages
https://user-images.githubusercontent.com/47526220/152645577-cf69974d-eacb-4892-be3d-715acc58506a.mp4

Nice melee tactics :o

**Comment by seymourimadeit** [comment]
Already exists.
