### ISSUE TITLE
make guards compatible with helmets with 3D models

### ISSUE THREAD

**Issue by 1Melone** [seymourimadeit/guardvillager-suggestions#95]
While playing I noticed that villager guards look pretty weird while wearing helmets with 3D models like the Wroughnout helmet from Mowzie's Mobs or the dragonscale helmets from Ice and Fire. Because the helmets are made to fit on a players head, the top of the guard's head sticks out from the helmet when wearing it. 
This could be fixed by giving the guards the steve model, but this takes a lot of this mod's aesthetic.

**Comment by seymourimadeit** [comment]
Due to the way minecraft models work this has to be done on the other mod's side.
